meta_product_name: "Secura"
meta_title: "Secura - Get five offers from our trusted partners in five easy steps"
meta_description: "Get five offers from our trusted partners in five easy steps. You're 10 clicks away from premiere security systems in your beloved home."
meta_image: "secura-logo-fb.png"                       # should exist in `app/assets/images/`
twitter_account: "@secura_dat_ass(;"   # required for Twitter Cards